### ISSUE TITLE
第二代播放器制作计划

### ISSUE THREAD

**Issue by QingXia-Ela** [QingXia-Ela/React-Small-Music-Player#2]
# 第二代播放器制作计划

**计划已开启**: https://github.com/QingXia-Ela/MonsterSirenPlayer

## 前言

距离我的第一个 React 音乐播放器上线已经过去了一个月了，在使用的过程中大部分地方都达到了我预期的效果，也有一些不满足的地方，比如功能太少，除了标准的听歌功能和使用歌单的功能基本就没有其他有特色的地方了，本人大概思考了一下播放器未来的发展方向，并决定在此提出未来第二代的制作计划。

### 基础目标

 - 支持多种登陆方式
 - 支持国际化
 - 用户定制选择需要的功能，并且这个定制选择的操作要简便
 - 重新打造 UI，追求简便但突出重要信息，强调听歌的氛围感与 “沉浸式” 氛围
 - 调整界面尺寸与部分区域大小，让用户拥有更好的交互体验
 - 可自定义主题与字体颜色，并设置为预置模板
 - 支持右键菜单弹出
 - 拥有自适应，支持电脑端与移动端
 - 对页面错误有更好的处理与捕获，最大程度保证不影响听歌氛围
 - 处理网易云变灰歌曲，可用其他平台音源替代
 - 支持蓝牙耳机事件处理
 - PWA 消息推送
 - 自定义功能快捷键

### 其他目标

 - 添加音频处理插件部分，用户可自定义音频输出效果
 - 桌面客户端与手机 APP 移植
 - 等待补充...

### 时间

时间计划是开发 1 ~ 2 年，包括从零开始的设计到初版发布

如果选择跟其他人自研后端部分可能要更久，但如果选择自研后端可能会有更多功能的添加

### 技术选型

前端部分是 UmiJs

如果有服务端渲染计划则同样使用其内置的服务端渲染功能

个人预期是能构建出一个标准的前端工作流，但限于本人能力可能还需要进行学习打磨

前端测试部分目前还在学习中，如果进度更新则本文会进行更新

**Comment by TOBYhhw** [comment]
智齿！

**Comment by RainMz** [comment]
是否可以支持播放webdav中的音乐

**Comment by QingXia-Ela** [comment]
> 是否可以支持播放webdav中的音乐

由于学业繁忙，软件不打算更新了，敬请谅解
