### ISSUE TITLE
关于播放器的bug

### ISSUE THREAD

**Issue by TOBYhhw** [QingXia-Ela/React-Small-Music-Player#3]
歌曲的详细页的播放按钮附件会有光标闪烁，播放歌曲时，返回上一页面后歌曲停止播放，切换歌曲时，加载异常，需要刷新后才能正常播放

**Comment by QingXia-Ela** [comment]
> 

有没有截图或者录屏，或者gif让我康康

**Comment by QingXia-Ela** [comment]
@TOBYhhw  有没有截图或者录屏，或者gif让我康康

**Comment by TOBYhhw** [comment]
![9e1521b75c23fc8818f990ea25d3ad9](https://user-images.githubusercontent.com/96869746/197333086-8ef003e2-e56e-4b12-9174-9ef4eaee7143.png)

**Comment by QingXia-Ela** [comment]
![图片](https://user-images.githubusercontent.com/86217807/197335333-66a6781e-ea09-4803-bf31-88f511dbb2c4.png)
